// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETxRQ5kZgoo4WY7zHwIO5gKLOfugVFJc',
    appId: '1:260199265172:web:f78ffb59a2797e5342d581',
    messagingSenderId: '260199265172',
    projectId: 'truth-dare-new',
    authDomain: 'truth-dare-new.firebaseapp.com',
    storageBucket: 'truth-dare-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7R_s73SSzt_vax_c0SBxPLc3AJyF2V4',
    appId: '1:260199265172:android:ee948acd8ffc992442d581',
    messagingSenderId: '260199265172',
    projectId: 'truth-dare-new',
    storageBucket: 'truth-dare-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekN1vS_naIPX2ApCNb05onzZX3dwgFo8',
    appId: '1:260199265172:ios:3ccd2fc61b2e485d42d581',
    messagingSenderId: '260199265172',
    projectId: 'truth-dare-new',
    storageBucket: 'truth-dare-new.firebasestorage.app',
    iosBundleId: 'com.example.truthDare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekN1vS_naIPX2ApCNb05onzZX3dwgFo8',
    appId: '1:260199265172:ios:3ccd2fc61b2e485d42d581',
    messagingSenderId: '260199265172',
    projectId: 'truth-dare-new',
    storageBucket: 'truth-dare-new.firebasestorage.app',
    iosBundleId: 'com.example.truthDare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDETxRQ5kZgoo4WY7zHwIO5gKLOfugVFJc',
    appId: '1:260199265172:web:35e971356092014f42d581',
    messagingSenderId: '260199265172',
    projectId: 'truth-dare-new',
    authDomain: 'truth-dare-new.firebaseapp.com',
    storageBucket: 'truth-dare-new.firebasestorage.app',
  );
}
